server:
  servlet:
    context-path: /shop
  port: 8080
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.107:3306/shop?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

  redis:
    host: 192.168.1.110
    port: 6379
    password: 123456
    jedis:
      pool:
        max-wait: 1000
        max-active: 5
        max-idle: 1
  data:
    mongodb:
      uri: mongodb://192.168.1.121:27017
      database: test
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672