package com.jk.model.djh;

public class Adminuser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminuser.uid
     *
     * @mbggenerated Tue Oct 30 19:44:26 CST 2018
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminuser.username
     *
     * @mbggenerated Tue Oct 30 19:44:26 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminuser.password
     *
     * @mbggenerated Tue Oct 30 19:44:26 CST 2018
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminuser.uid
     *
     * @return the value of adminuser.uid
     *
     * @mbggenerated Tue Oct 30 19:44:26 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminuser.uid
     *
     * @param uid the value for adminuser.uid
     *
     * @mbggenerated Tue Oct 30 19:44:26 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminuser.username
     *
     * @return the value of adminuser.username
     *
     * @mbggenerated Tue Oct 30 19:44:26 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminuser.username
     *
     * @param username the value for adminuser.username
     *
     * @mbggenerated Tue Oct 30 19:44:26 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminuser.password
     *
     * @return the value of adminuser.password
     *
     * @mbggenerated Tue Oct 30 19:44:26 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminuser.password
     *
     * @param password the value for adminuser.password
     *
     * @mbggenerated Tue Oct 30 19:44:26 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}